### PR TITLE
Enable Python 3 travis build

### PR DESCRIPTION
**Pull request by rodrigc**
Can you enable Travis builds of this repository at: https://travis-ci.org/profile/mathiasertl ?

### CODE REVIEW

**Comment by rodrigc** [comment]
@mathiasertl can you look at this PR and https://github.com/mathiasertl/fabric/pull/20 ?
Thanks.

**Comment by mathiasertl** [comment]
Thanks!

**Comment by nicktimko** [comment]
The `.travis.yml` file seems to be in order, but to actually make use of it (testing PRs, pushes) you need to setup an account (i.e. link to GitHub) at Travis and check this repo to enable builds.

https://travis-ci.org/

**Comment by mathiasertl** [comment]
Done. Travis says something will happen on the next commit :-)

**Pull request merged**
