### PR TITLE
Graft 1.10 --> 1.11 from Fabric onto Fabric3

### PR DESCRIPTION
**Pull request by nicktimko**
A couple minor merge conflicts fixed (version number, bugfix in fabric/fabric that touched the same line as the deprecated isMappingType thing, and dev-requirements.txt)

### CODE REVIEW

**Comment by mathiasertl** [comment]
Why is this pull request against the 1.10 branch? Are there any changes to the master branch?

**Comment by nicktimko** [comment]
[I have no idea what I'm doing.jpg](http://i.imgur.com/l3v4P3s.jpg). Probably should just have made an issue and let you merge it :expressionless:

**Comment by mathiasertl** [comment]
Hey wait a minute. I didn't realize that there was a new upstream Fabric release and that 1.11 is a new version. Thanks a lot for the work - will check this out right away!

**Comment by mathiasertl** [comment]
I'm closing the pull request, 1.11.1.post1 has been released.

**Pull request closed without merging**
