### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Provide a Dockerfile that users can use when a base environment is required for programmatic usage (eg: some CI services that use docker containers).

By linking thing to automated docker hub builds, ready-made images can be provided.

### CODE REVIEW

**Comment by nicktimko** [comment]
What's the purpose of this versus just adding `fabric3` into a requirements.txt file? If you use this as a dependency, you lose any flexibility of the underlying distro (slim, alpine, etc.) at the expense of adding a layer for a single `pip install`.

**Comment by mathiasertl** [comment]
@WhyNotHugo I'm also not quite sure what the potential use for this is. BUT I haven't used docker that much yet, so I'm open to the improvement. Can you share your usecase?

**Comment by WhyNotHugo** [comment]
@nicktimko Creating a `requirements.txt` file with just fabric3 is practically the same as running `pip install fabric3`. The idea of having a pre-built docker image is to save a bit of time by not performing the installation each time.

@mathiasertl Personally, I'm using this for GitLab CI, which uses docker images as bases for running jobs. My deployment job uses fabric3, so I just use this as a base, and don't have to include the installation of it on each run.
Since images are cached, this ends up saving a bit of time each run.

I'd happily add the relevant docs if this is deemed acceptable.

**Comment by nicktimko** [comment]
Unless you're using the base Python image with that single `RUN pip install Fabric3` layer on top, I'm confused how it's an improvement. Do you use any other packages, either for Python or the distribution? Do you copy any code into the container?

If your dependencies are fairly constant, a common pattern in lieu of 
```
COPY requirements.txt
RUN pip install -r requirements.txt
```

which I think can be considered 'slow' because the `COPY` seems to invalidate the cache, is to just explicitly install things in the Dockerfile:
```
RUN pip install fabric3==1.11.post1 \
                pytest==3.2.1 \
                django==1.11
```

That will create a single layer that gets cached. Additionally, combining them into a single command is *far preferable* to multiple a la:
```
RUN pip install fabric3==1.11.post1
RUN pip install pytest==3.2.1
RUN pip install django==1.11
```

because you only have one layer.

Is there some other prior art along your line that just `pip install`'s a single package and that's promoted as a use? I could imagine it for libraries that have uncommon/difficult-to-install dependencies.

**Comment by WhyNotHugo** [comment]
@nicktimko Your entire argument seems to orbit around the idea that I'm already creating a custom image. Like I said before: I'm not. My current setup uses `python:3.6`, and I install fabric 3 every single time.

One of my current scenarios is GitLab's CI. GitLab CIIt uses a defined docker image, and runs `.gitlab-ci.yaml` (eg: deploys code).

While I can, of course, install fabric3 every *single time I deploy code*, using an existing `fabric3` image to use as a base is faster (especially since the CI runner will cache the image locally).

**Comment by nicktimko** [comment]
Can you give me an example (link to a Dockerfile)?

**Pull request closed without merging**
